EhodVenteEnLigne/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using EhodBoutiqueEnLigne.Models;

namespace EhodBoutiqueEnLigne.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private readonly Cart _cart;

        public CartSummaryViewComponent(ICart cart)
        {
            _cart = cart as Cart;
        }

        public IViewComponentResult Invoke()
        {
            return View(_cart);
        }
    }
}

EhodVenteEnLigne/Components/LanguageSelectorViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using EhodBoutiqueEnLigne.Models.Services;

namespace EhodBoutiqueEnLigne.Components
{
    public class LanguageSelectorViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(ILanguageService languageService)
        {
            return View(languageService);
        }
    }
}

EhodVenteEnLigne/Controllers/LanguageController.cs
using Microsoft.AspNetCore.Mvc;
using EhodBoutiqueEnLigne.Models.Services;
using EhodBoutiqueEnLigne.Models.ViewModels;

namespace EhodBoutiqueEnLigne.Controllers
{
    public class LanguageController : Controller
    {
        private readonly ILanguageService _languageService;

        public LanguageController(ILanguageService languageService)
        {
            _languageService = languageService;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ChangeUiLanguage(LanguageViewModel model, string returnUrl)
        {
            if (model.Language != null)
            {
                _languageService.ChangeUiLanguage(HttpContext, model.Language);
            }

            return Redirect(returnUrl);
        }
    }
}

EhodVenteEnLigne/Views/Shared/Components/LanguageSelector/Default.cshtml
@model EhodBoutiqueEnLigne.Models.ViewModels.LanguageViewModel

<form asp-action="ChangeUiLanguage" asp-controller="Language" method="post">
    <div class="row align-items-center">
        <label class="col-md-3 control-label">@Localizer["Language"]</label>
        <div class="col-md-7">
            <select asp-for="Language" class="form-select">
                <option disabled selected style="font-style:italic">@Localizer["ChangeLanguage"]</option>
                <option value="English">@Localizer["LanguageEnglish"]</option>
                <option value="French">@Localizer["LanguageFrench"]</option>
                <option value="Wolof">@Localizer["LanguageWolof"]</option>
            </select>
        </div>
        <div class="col-md-2">
            <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.Path" />
            <button class="btn btn-info" type="submit"> OK </button>
        </div>
    </div>
</form>