EhodVenteEnLigne/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using EhodBoutiqueEnLigne.Models;

namespace EhodBoutiqueEnLigne.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private readonly Cart _cart;

        public CartSummaryViewComponent(ICart cart)
        {
            _cart = cart as Cart;
        }

        public IViewComponentResult Invoke()
        {
            return View(_cart);
        }
    }
}

EhodVenteEnLigne/Components/LanguageSelectorViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using EhodBoutiqueEnLigne.Models.Services;

namespace EhodBoutiqueEnLigne.Components
{
    public class LanguageSelectorViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(ILanguageService languageService)
        {
            return View(languageService);
        }
    }
}

EhodVenteEnLigne/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using EhodBoutiqueEnLigne.Models.Services;
using EhodBoutiqueEnLigne.Models.ViewModels;
using System.Collections.Generic;
using System.Linq;

namespace EhodBoutiqueEnLigne.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly ILanguageService _languageService;

        public ProductController(IProductService productService, ILanguageService languageService)
        {
            _productService = productService;
            _languageService = languageService;
        }

        public IActionResult Index()
        {
            IEnumerable<ProductViewModel> products = _productService.GetAllProductsViewModel();
            return View(products);
        }

        [Authorize]
        public IActionResult Admin()
        {
            return View(_productService.GetAllProductsViewModel().OrderByDescending(p => p.Id));
        }

        [Authorize]
        public ViewResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public IActionResult Create(ProductViewModel product)
        {
            List<string> modelErrors = _productService.CheckProductModelErrors(product);           

            foreach (string error in modelErrors)
            {
                ModelState.AddModelError("", error);
            }

            if (ModelState.IsValid)
            {
                _productService.SaveProduct(product);
                return RedirectToAction("Admin");
            }
            else
            {
                return View(product);
            }
        }

        [Authorize]
        [HttpPost]
        public IActionResult DeleteProduct(int id)
        {
            _productService.DeleteProduct(id);
            return RedirectToAction("Admin");
        }
    }
}

EhodVenteEnLigne/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet"
          asp-href-include="/lib/bootstrap/css/bootstrap.min.css"
          asp-href-exclude="**/*-reboot*,**/*-grid*" />
    <title>@ViewBag.Title</title>
    <script src="/lib/jquery/dist/jquery.min.js"></script>
    <script src="/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js">
    </script>
</head>
<body>
    <div class="bg-warning p-2 row">
        <div class="col" style="padding-left:12%">
            <h4>@ViewBag.Title</h4>
        </div>
        <div class="col-2">
            <a class="btn btn-sm btn-primary"
               asp-action="Logout" asp-controller="Account">@Localizer["Logout"]</a>
        </div>
    </div>
    @if (TempData["message"] != null)
    {
        <div class="alert alert-success mt-1">@TempData["message"]</div>
    }
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <div class="row">
                <div class="col-8"><p style="padding-top:17px">&copy; 2022 - EhodVenteEnLigne</p></div>
                <div class="col-4">
                    @await Component.InvokeAsync("LanguageSelector")
                </div>
            </div>
        </footer>
    </div>
</body>
</html>

EhodVenteEnLigne/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet"
          asp-href-include="/lib/bootstrap/**/*.min.css"
          asp-href-exclude="**/*-reboot*,**/*-grid*" />
    <link rel="stylesheet" asp-href-include="/lib/fontawesome/css/*.css" />
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <title>@ViewData["Title"] - EhodBoutiqueEnLigne</title>
</head>
<body>
    <div class="bg-primary py-2">
        <div class="container-fluid">
            <div class="row align-items-center">
                <div class="col">
                    <a class="btn btn-warning" asp-action="Admin" asp-controller="Product">
                        @Localizer["Administrator"]
                    </a>
                </div>
                <div class="col-7">
                    <a class="navbar-brand text-white fs-4" asp-action="Index" asp-controller="Product">
                        Ehod Vente en Ligne
                    </a>
                </div>          
                <div class="col">
                    @await Component.InvokeAsync("CartSummary")
                </div>

            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <div class="row">
                <div class="col-8"><p>&copy; 2023 - Ehod Vente de Produits EnLigne</p></div>
                <div class="col-4">
                    @await Component.InvokeAsync("LanguageSelector")
                </div>
            </div>
        </footer>
    </div>

    @RenderSection("Scripts", required: false)
</body>
</html>